FROM apache/airflow:3.3.0-python3.13

USER root

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
COPY --from=ghcr.io/astral-sh/uv:latest /uvx /usr/local/bin/uvx

USER airflow

WORKDIR /opt/airflow

COPY --chown=airflow:root pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY --chown=airflow:root . .

ENV PATH="/opt/airflow/.venv/bin:$PATH"